version: '3.9'

services:
  go-app:
    container_name: go-app
    image: yurisalesc/go-app:1.0.0
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql@12/data:rw

volumes:
  pgdata: {}